"""Add product active flag

Revision ID: 21e8c37f73be
Revises: 6b32e2e320dd
Create Date: 2026-10-07 19:55:53.500515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21e8c37f73be'
down_revision: Union[str, Sequence[str], None] = '6b32e2e320dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'products',
        sa.Column(
            'is_active',
            sa.Integer(),
            nullable=False,
            server_default='1'
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_active')
    # ### end Alembic commands ###
