"""Add delivery address to orders

Revision ID: da386b4b7e04
Revises: 21e8c37f73be
Create Date: 2026-10-07 20:19:20.769498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da386b4b7e04'
down_revision: Union[str, Sequence[str], None] = '21e8c37f73be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "orders",
        sa.Column(
            "delivery_address",
            sa.String(length=500),
            nullable=True
        )
    )

    op.execute(
        "UPDATE orders SET delivery_address = 'Не указан' "
        "WHERE delivery_address IS NULL"
    )

    op.alter_column(
        "orders",
        "delivery_address",
        nullable=False
    )

    
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_address')
    # ### end Alembic commands ###
